### ISSUE TITLE
Epic: Core backend

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#12]
Create the main service that will communicate with the DB, expose API, schedule games and in general do the main backend related things.

## Milestone I - base
* [ ] create backend project #4 
* [ ] setup basic infrastructure #3 

## Milestone II - user system
* [ ] backend support for user systems #5 
* [ ] API user profile
* [ ] API user settings

## Milestone III - bots
* [ ] add bots to db schema
* [ ] bot storage
* [ ] bot pipeline
    * [ ] queing new bots
    * [ ] prepare bot
    * [ ] handle resource limitations (how many bots can be preparing at the same time?)
* [ ] API bots endpoints 

## Milestone IV - games
* [ ] add games to db schema
* [ ] link bots to specific games
* [ ] store game metadata (description, etc.)
* [ ] match generation pipeline
    * [ ] test match queue
    * [ ] generate test match
    * [ ] match queue
    * [ ] generate match
    * [ ] handle resource limitations 
        * [ ] how many matches to generate at the same time
        * [ ] sync with bot preparation limitations and requirements
* [ ] API get list of matches for specific games 
* [ ] API list of matches filter support
* [ ] API for game(s) details

## Milestone V - leaderboards
* [ ] add leaderboars metadata to db schema
* [ ] multiple leaderboard support
* [ ] link bots to leaderbaords
* [ ] generate leaderboards for games
* [ ] leaderboard caching
* [ ] API display leaderboard
