### ISSUE TITLE
Epic: DevOps

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#14]
Help to make developers life easier.

## Milestone I - CI/CD
* [ ] github actions when commited to master
* [ ] backend services test and deploy
* [ ] website test and deploy
* [ ] documentation test and deploy
* [ ] games test and deploy
* [ ] infrastructure files deploy 
* [ ] CLI test, build and create a new release
* [ ] game utilities - test, build and deploy libraries to remote center (eg. Maven central)

## Milestone II - monitoring
* [ ] unified logs view across all services
* [ ] monitoring dasboard (performance, health, ...)
* [ ] alerting
