### ISSUE TITLE
Epic: Planet Lia docs

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#15]
Main documentation page for the Planet Lia platform.

## Milestone I - Development
- [ ] Navbar that supports multiple levels (eg. main->games->game-name->examples)
    - Research: seperate page for games vs deep navbar nesting
- [ ] Rebranding and upgrading looks

## Milestone II - Content
- [ ] General docs
- [ ] CLI
- [ ] Getting started guide
- [ ] How to create games guide
- [ ] Guides for specific games
- ...
