### ISSUE TITLE
Epic: Local match viewer

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#16]
Create a local website that can display local matches.

## Milestone I
- [ ] Create the site and integrate match viewer in it
- [ ] Load replay files from local os
- [ ] Refresh match when CLI requires it to replay another match
- [ ] List all replay files
