### ISSUE TITLE
Epic: Main website

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#17]
Create a new website.

## Milestone I - Base
- [ ] Setup [template](https://themeforest.net/item/indiega-gaming-html-template/22289825)
- [ ] Registration
- [ ] Log in
- [ ] Log out
- [ ] Authentication
- [ ] Profile 
- [ ] Profile settings
- [ ] Landing page

## Milestone II - Core
- [ ] Games page
- [ ] Game page
- [ ] Tournaments page
- [ ] Contributing page
- [ ] Match page
- [ ] Profile statistics and details

## Milestone II - Online Editor
- [ ] Generic support for different languages
- [ ] Generic support for different games
- [ ] Save code to backend (multiple bots for different games?)
- [ ] View game API docs
- [ ] Battle against yourself
- [ ] Battle against basic bot
- [ ] Submit bot to the leaderboard
