### ISSUE TITLE
Epic: Online editor

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#53]
Migrate online editor to support multiple games on a new infrastructure as well as developing two bots at the same time.

## Backend
- [ ] Listen for online editor match requests
- [ ] Prepare docker image with prebaked bots and game(s)
- [ ] Inject MyBot files to prebaked bots 
- [ ] Support two bot files at the same time
- [ ] Run match and return replay
- [ ] Stream stdout
- [ ] Support multiple match generations at the same time
- [ ] Rate limiting
- [ ] Handle resource limitations

## Frontend
- [ ] Not bind to one game (generic)
- [ ] Fetch bots for specified game
- [ ] Get API links for specified games
- [ ] Support 2 tabs for two bots
- [ ] Send both bots to backend to generate the match
- [ ] Polling stdout and replay file
- [ ] Display replay file
