### ISSUE TITLE
Epic: User system

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#54]
Create a user system on backend and frontend to support generic user functionalities as well as Discourse synchronization.

## Backend
- [ ] Database scheme
- [ ] Email verification
- [ ] Account registration
- [ ] Token creation
- [ ] Login
    - [ ] Normal
    - [ ] Via GitHub
- [ ] Logout
- [ ] Profile CRUD
    - [ ] Profile image 
    - [ ] Name, surename, organization, settings, ...
- [ ] Upload bot via online editor
- [ ] Discourse integration

## Frontend
- [ ] Registration
- [ ] Login
    - [ ] Normal
    - [ ] Via GitHub
- [ ] Logout
- [ ] Profile page
    - [ ] Base user data
    - [ ] Display and update profile image
- [ ] Upload bot via online editor
