### ISSUE TITLE
Epic: Challenges

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#55]
Implement support for challenging other users on the platform.

## Backend
- [ ] Pipeline
    - [ ] Prepare docker image for bot preparation (Ubuntu)
    - [ ] Prepare bot
    - [ ] Prepare docker image for running bot (called bot environment - is versioned) (Ubuntu)
         - [ ] Bots can choose in which environment version they run (prebaked dependencies)
    - [ ] Run test match
    - [ ] Run match
    - [ ] Store match results, logs and replay files
    - [ ] Queue for new bots
    - [ ] Queue for challenges
- [ ] Challenges supporting multiple games 
- [ ] Rate limiting (how many challenges per day)
- [ ] Resource management 
- [ ] API
    - [ ] Bot status
    - [ ] Bot logs
    - [ ] List of user challenges (with filters)
    - [ ] Match data
    - [ ] Match replay

## Frontend
- [ ] List of player challenges on profile
- [ ] Match view
- [ ] Bot status on profile
- [ ] Bot logs download option on profile
- [ ] List of all matches (?)
