### ISSUE TITLE
Epic: Leaderboard

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#56]
Support for multiple leaderboards on backend with a single leaderboard displayed on frontend.

## Backend
- [ ] Simple matchmaking that generates many matches on random (for all games?)
- [ ] Leaderboard generation for all games 
- [ ] API
    - [ ] List of all matches for a specific game
    - [ ] List of all matches for a specific game for a specific player 
    - [ ] Leaderboard

## Frontend
- [ ] Leaderboard view
- [ ] Matches view for one game
- [ ] User matches list for specific game on user profile
