### ISSUE TITLE
Epic: Matchmaking

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#57]
Actual dynamic matchmaking implementation.

## Backend
- [ ] Match scheduler
- [ ] Queuing matches
- [ ] Support multiple games
- [ ] Resource limitation
- [ ] Expose configuration endpoint for tweaking matchmaking for each leaderboard
- [ ] Cleaning up stuck matches

## Frontend
- [ ] Details on how many matches are being played / waiting to be played
