### ISSUE TITLE
Epic: Platform stress testing

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#58]
Test how platform behaves under load.

## Backend
- [ ] Register 1000+ users
- [ ] Write a script that will upload bots for many users 
- [ ] See how system works under load
- [ ] Play with matchmaking configuration
    - [ ] 100% resource utilization
    - [ ] 80% resource utilization etc.
- [ ] Wait until many games are generated 
- [ ] Test performance of pages
    - [ ] Leaderboard
    - [ ] Profile page
    - [ ] Matches view
