### ISSUE TITLE
Epic: Old game archives

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#59]
Integrate old games/tournaments (eg. SLT2019) into the new platform and display them as archived tournaments.

## Backend
- [ ] Integrate old games and create archived tournaments for them
- [ ] Expose old matches 
- [ ] Add online editor support for those games

## Frontend
- [ ] Docs support for multiple games (navbar!)
- [ ] Display tournaments
    - [ ] Tournament page
    - [ ] Online editor support
    - [ ] Leaderboard
    - [ ] Matches list
    - [ ] Different bot profile pages for different tournaments
 - [ ] Profile page displaying multiple games (matches, bots, stats)
 - [ ] Games page displaying current game
