### ISSUE TITLE
Epic: SLT2020

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#60]
Prepare everything code related for SLT2020.

## Game
- [ ] Create main game
- [ ] Docs for main game
- [ ] Add new languages
    - [ ] Javascript
    - [ ] C#
    - [ ] C++

## Backend
- [ ] Add support for main game
