### ISSUE TITLE
Epic: Community games

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#62]
## Backend
- [ ] Multiple games support
- [ ] Community games support

## Frontend
- [ ] Multiple games support
- [ ] Community games support

## Games 
- [ ] Create demo game 
- [ ] Create demo game dev tutorials
   - [ ] Written
   - [ ] Video
- [ ] Help community members to create at least 1 community game
