### ISSUE TITLE
Epic: Rewrite Lia-1 (SLT2019) game to new framework

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#63]
Rewrite Lia-1 game used for SLT2019 to new game development framework.

## Game
* [ ] Migrate Lia-1 game to the new framework
    * [ ] Improve performance (ideally under 1 s per game generation)
* [ ] Write specific starting bot implementations
    * [ ] Java
    * [ ] Kotlin
    * [ ] Python3
