### ISSUE TITLE
Epic: Game dev framework

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#7]
Create a game development framework which will help developers creating Planet Lia games to more easily create their own games.

## Game (Example Game)
* [x] Base LibGDX project #20 
* [x] Main loop that can run with or without (debug view) displaying the game #21
* [x] Support any number of connected bots #22
* [x] Bot restrictions support #23
* [x] Add generic config support (loads a config)  #35
* [x] Generic way of getting game state every tick (for custom tools) - Discord request #40 
* [x] Add support for teams of bots #42 
* [x] Pass through bot details to bots eg. who are his opponents and optionally ranks, link to external storage etc. #43 
* [x] Log window in debug view where bots can write their logs #24
* [x] Debug view controls (play, pause, speed) #78
* [x] Debug view disable bot restrictions #79
* [x] Base entity that devs can extend and that can display entity details on hover #80
* [x] Basic bot API #90
* [x] Support for writing replay files #81
* [x] Write bot runtime stats to replay file (standarize it!). Examples: number of timeouts, was it disqualified, disqualification time, response total duration, disqualification reason, team index #82
* [x] Rename game-template to game-example #96
* [x] Remove default bots and implement Java and Kotlin for this example #97
* [ ] Document game-example #83 

## Game Utils
* [x] Match viewer remove the need to specify file type (gzip, json, zip)
* [ ] Export generic functions to library #98
* [ ] Document library
* [x] Refactor basic bot implementations to be generic for any game
    * [x] Java #25 
    * [x] Kotlin #87
    * [x] Python3 #88
* [ ] Tutorial on how to add new generic bot implementation for unsupported languages

**Comment by svigelj** [comment]
Missing tasks won't be implemented as they are not a priority.
