### ISSUE TITLE
Epic: Offline Tournament Environment

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#76]
Support for generating local leaderboard and packing it with all games into a static html page.

## Local Environment - Backend
- [ ] Map uploaded bots to usernames and emails
- [ ] Generate matches in parallel
- [ ] Store results of matches
- [ ] Keep track of the leaderboard
- [ ] Define matchmaking logic

## Local Environment - Frontend
- [ ] Leaderboard page
- [ ] Games page 
- [ ] Games page filter by user
- [ ] Deploy website
