### ISSUE TITLE
Epic: Improve bot languages support

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#8]
Improve the current bot language implementations and add new ones. 
Make sure that basic bot for each language can by default support any Planet Lia game.

## Milestone I
* [ ] add Javascript generic bot
* [ ] add C# generic bot
* [ ] add C++ generic bot
* [ ] all bots should support any Planet Lia game by default

## Supporting tasks
* [ ] tutorial on how to support new languages
* [ ] tutorial on how to improve generic bot implementations to better support a specific Planet Lia game
* [ ] research: using websocket wrapper and using stdout to communicate with it
