### ISSUE TITLE
Epic: CLI improvements

### ISSUE THREAD

**Issue by svigelj** [planet-lia/planet-lia#9]
Improve CLI to support multiple Planet Lia games and better bot development workflow.

## Milestone I (overview)
* [ ] support multiple games
* [ ] generate multiple games asynchronously
* [ ] use a web based replay viewer

## Milestone II
List of CLI commands (not final nor complete):

* [ ] game
    * [ ] download
    * [ ] set 
    * [ ] list
    * [ ] update
    * [ ] delete
* [ ] bot
    * [ ] new
    * [ ] update
    * [ ] delete
    * [ ] upload
* [ ] play
* [ ] replay
* [ ] help 
* [ ] settings
* [ ] account
    * [ ] login
    * [ ] logout
    * [ ] status
